"""initial schema

Revision ID: 53d8f3192d88
Revises: 
Create Date: 2026-06-04 13:13:55.462108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d8f3192d88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=255), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=True),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('app', sa.String(length=255), nullable=True),
    sa.Column('window_title', sa.Text(), nullable=True),
    sa.Column('project', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('start_ts', sa.String(length=40), nullable=True),
    sa.Column('end_ts', sa.String(length=40), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'start_ts', 'app', 'window_title', 'state', name='uq_segment')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index('idx_emp', ['employee_id'], unique=False)
        batch_op.create_index('idx_start', ['start_ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index('idx_start')
        batch_op.drop_index('idx_emp')

    op.drop_table('segments')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
